name: lockre
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0' # Compatible with Dart SDK 2.15.0

dependencies:
  flutter:
    sdk: flutter
 
  meta: ^1.7.0
  cupertino_icons: ^1.0.2
  get: ^4.6.1
 
  numeric_keyboard: ^1.0.0
  pin_code_fields: ^8.0.1
  pin_code_view: ^0.3.0+2
  permission_handler: ^10.2.0
  
  currency_picker: ^2.0.19
 
  font_awesome_flutter: ^9.1.0
  shake: ^2.2.0
  share: ^2.0.4
  ussd_service: ^0.1.1
  flag: ^6.0.0 # Updated to match available versions
  shared_preferences: ^2.0.13
  
  
  
  email_validator: ^3.0.0

  
  introduction_screen: ^3.1.14
  path: ^1.8.0

  

  flutter_signin_button: ^2.0.0
  
  
  path_provider: ^2.0.11
  provider: ^6.0.4
 
  
  animated_widgets: ^1.1.0

  lottie: ^1.0.1
  flutter_translate: ^4.0.4
  
  device_apps: ^2.2.0
  
  
  
  http: ^0.13.4

  whatsapp_unilink: ^2.1.0
  

dependency_overrides:
  collection: ^1.17.2



flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icon/
    - assets/image/
    - assets/
